name: Build binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write    # <-- allow creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make zlib1g-dev

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: genome-cdbg-paths-linux
          path: genome-cdbg-paths

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*
